version: '3.5'

services:
  site:
    image: jekyll/jekyll
    working_dir: /opt
    command: [ 'jekyll', 'serve', '--livereload' ]
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: host
      - target: 35729
        published: 35729
        protocol: tcp
        mode: host
    volumes:
      - .:/opt:rw
